### ISSUE TITLE
Without valid ASIN, running first time fails gracefully, but subsequent runs fail hard

### ISSUE THREAD

**Issue by stoduk** [stoduk/calibre_plugin_xray#22]
Fix #7 seemed relevant, but isn't (that was a change between print and sys.stdout.write - which should be practically the same thing).  With print we get a IOError(32, "Broken Pipe"); with sys.stdout.write we get IOError(0, "Error").

So to reproduce this, run the script on a book without a valid ASIN twice - first time you'll get the usual error message about it (which happens in the worker thread), the second and subsequent runs will hit the  logging problem about (which happens before the worker thread is spawned).

Not sure what is special about this error case vs. others - maybe nothing..

Note: restarting Calibre resets the problem, and obviously fixing the book's ASIN sorts things out.  This is a bug in error handling (or at least, a bug on seen in error handling so far).

```
calibre, version 2.44.1
ERROR: Unhandled exception: <b>IOError</b>:[Errno 0] Error

calibre 2.44.1  isfrozen: True is64bit: True
Darwin-14.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.5.0', 'Darwin Kernel Version 14.5.0: Tue Sep  1 21:23:09 PDT 2015; root:xnu-2782.50.1~1/RELEASE_X86_64')
Python 2.7.9
OSX: ('10.10.5', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM && Goodreads && XRay Generator && Quality Check
Traceback (most recent call last):
  File "calibre_plugins.xray_generator.xrayaction", line 73, in generate_selected
  File "calibre_plugins.xray_generator.xrayaction", line 116, in _generate_selected
  File "calibre_plugins.xray_generator.xrayaction", line 431, in generate_xray
  File "calibre_plugins.xray_generator.lib.kindleunpack", line 1662, in unpackBook
  File "calibre_plugins.xray_generator.lib.kindleunpack", line 1145, in process_all_mobi_headers
  File "calibre_plugins.xray_generator.lib.kindleunpack", line 937, in dumpheader
IOError: [Errno 0] Error
```

**Comment by stoduk** [comment]
This bug is being a real PITA.  It really gets in the way of testing, as when it is around you can only do one run of the script before you have to restart calibre.  But now I've gone to try to track it down and I can't reproduce it any more!  [I can reproduce it with secondary account on laptop, and using the plugin from Matthew; earlier today with my primary account and the latest dev version I could reproduce it every time but now it doesn't hit the problem]

Some notes:
- the problem is happening in a call to print/sys.stdout (and depending which we seem to get "broken pipe" or the rather odd IOError(0) assertion)
- adding a call to print in generate_selection (the entry point) did always cause the exception to be hit straight away on the second run
- I can see that we are trying to write to stdout rather than a file (so I don't think we've got any oddness with anything having assigned a file type object to sys.stdout).  The fact it triggers a broken pipe error suggests to me that calibre is spawning our script in a subprocess and reading the stdout from another process - not found where that happens yet (or if that guess is right)

**Comment by stoduk** [comment]
Looking bag, issue #7 had a very similar problem and in that case I thought the issue was excessive output.  'chaley' on the forums initially suggested the same possible problem here, but seemed less convinced when I said I wasn't using Windows.  However, I'm now suspicious given I "fixed" the problem before..

For now I'll reduce the output the plugin makes and see how that impacts things.

Interestingly: doing a tight loop of print or job.log_write doesn't cause the problem to be seen, suggesting it isn't quite so straight forward.  But perhaps I need other system activity (CPU or disk intensive) to happen at the same time for things to crap out.
