### ISSUE TITLE
Traceback when (re-)running X-Ray Generator on certain books

### ISSUE THREAD

**Issue by stoduk** [stoduk/calibre_plugin_xray#7]
I've only seen this problem on re-running the tool and then only on a certain file.  I think the problem is that the dump option to kindleunpack.py is both causing more information to be unpacked but also printing a lot to stdout.

In this case the book (A Christmas Carol by Charles Dickens, from Project Gutenburg) seems to hit the error message where unknown data is found and printed.  However the information is all zeros and of no interest at all.

I think the excessive printing is causing some upstream problem - I assume somewhere Calibre is creating a pipe to the plugin element which does not have a large enough buffer, so that when it is overfilled (by excessive print'ing) then the problem is hit.

```
calibre, version 2.40.0
ERROR: Unhandled exception: <b>IOError</b>:[Errno 32] Broken pipe

calibre 2.40  isfrozen: True is64bit: True
Darwin-14.5.0-x86_64-i386-64bit Darwin ('64bit', '')
('Darwin', '14.5.0', 'Darwin Kernel Version 14.5.0: Wed Jul 29 02:26:53 PDT 2015; root:xnu-2782.40.9~1/RELEASE_X86_64')
Python 2.7.9
OSX: ('10.10.5', ('', '', ''), 'x86_64')
Successfully initialized third party plugins: DeDRM && Quality Check && Goodreads && XRay Generator
Traceback (most recent call last):
  File "calibre_plugins.xray_generator.xrayaction", line 76, in generate_selected
  File "calibre_plugins.xray_generator.xrayaction", line 118, in _generate_selected
  File "calibre_plugins.xray_generator.xrayaction", line 405, in generate_xray
  File "calibre_plugins.xray_generator.lib.kindleunpack", line 1638, in unpackBook
  File "calibre_plugins.xray_generator.lib.kindleunpack", line 1121, in process_all_mobi_headers
  File "calibre_plugins.xray_generator.lib.kindleunpack", line 918, in dumpheader
IOError: [Errno 32] Broken pipe
```

**Comment by stoduk** [comment]
Hacking the kindkeunpack.py code to print less output seems to fix the issue, suggesting that my suspicion is correct even if I don't have the full details of the Calibre:plugin connection :)
